/* This file is generated by scripts/prepare-blog-manifest.mjs. */
import { post as post01 } from "../blog/(entries)/(01_memory-layout-for-react-devs)/memory-layout-for-react-devs/page";

export const blogEntries = [
  { directory: "(01_memory-layout-for-react-devs)", publicSlug: "memory-layout-for-react-devs", post: post01 },
] as const;
